"""production schema

Revision ID: 05782a7e01c8
Revises: 
Create Date: 2026-09-14 20:08:17.038496
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '05782a7e01c8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_hi', sa.String(length=200), nullable=False),
    sa.Column('ministry', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('policies',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('title_hi', sa.String(length=400), nullable=False),
    sa.Column('issuing_body', sa.String(length=300), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('code', name=op.f('uq_policies_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_hi', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code IN ('CITIZEN', 'STUDENT', 'CSC_OPERATOR', 'WELFARE_OFFICER', 'POLICY_ANALYST', 'ADMIN')", name=op.f('ck_roles_role_code')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('states',
    sa.Column('lgd_code', sa.Integer(), nullable=False),
    sa.Column('iso_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_hi', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('STATE', 'UT')", name=op.f('ck_states_kind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_states')),
    sa.UniqueConstraint('iso_code', name=op.f('uq_states_iso_code')),
    sa.UniqueConstraint('lgd_code', name=op.f('uq_states_lgd_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("action IN ('login', 'logout', 'role_change', 'profile_update', 'profile_purge', 'ingestion_run', 'review_approve')", name=op.f('ck_audit_logs_action')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('districts',
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_districts_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('lgd_code', name=op.f('uq_districts_lgd_code')),
    sa.UniqueConstraint('state_id', 'name', name=op.f('uq_districts_state_id'))
    )
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('internships',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_hi', sa.String(length=300), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('state_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived', 'needs_review')", name=op.f('ck_internships_status')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_internships_department_id_departments')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_internships_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internships'))
    )
    op.create_index(op.f('ix_internships_content_hash'), 'internships', ['content_hash'], unique=False)
    op.create_index(op.f('ix_internships_deadline'), 'internships', ['deadline'], unique=False)
    op.create_index(op.f('ix_internships_department_id'), 'internships', ['department_id'], unique=False)
    op.create_index(op.f('ix_internships_state_id'), 'internships', ['state_id'], unique=False)
    op.create_table('jobs',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_hi', sa.String(length=300), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('state_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived', 'needs_review')", name=op.f('ck_jobs_status')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_jobs_department_id_departments')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_jobs_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_deadline'), 'jobs', ['deadline'], unique=False)
    op.create_index(op.f('ix_jobs_department_id'), 'jobs', ['department_id'], unique=False)
    op.create_index(op.f('ix_jobs_state_id'), 'jobs', ['state_id'], unique=False)
    op.create_table('schemes',
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('state_id', sa.Uuid(), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('agriculture', 'women', 'education', 'health', 'msme', 'other')", name=op.f('ck_schemes_category')),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived', 'needs_review')", name=op.f('ck_schemes_status')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_schemes_department_id_departments')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_schemes_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schemes')),
    sa.UniqueConstraint('code', name=op.f('uq_schemes_code')),
    sa.UniqueConstraint('slug', name=op.f('uq_schemes_slug'))
    )
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_department_id'), 'schemes', ['department_id'], unique=False)
    op.create_index(op.f('ix_schemes_state_id'), 'schemes', ['state_id'], unique=False)
    op.create_index(op.f('ix_schemes_status'), 'schemes', ['status'], unique=False)
    op.create_table('scholarships',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_hi', sa.String(length=300), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('state_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('income_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived', 'needs_review')", name=op.f('ck_scholarships_status')),
    sa.CheckConstraint('income_limit IS NULL OR income_limit >= 0', name=op.f('ck_scholarships_income_non_negative')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_scholarships_department_id_departments')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_scholarships_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scholarships'))
    )
    op.create_index(op.f('ix_scholarships_content_hash'), 'scholarships', ['content_hash'], unique=False)
    op.create_index(op.f('ix_scholarships_deadline'), 'scholarships', ['deadline'], unique=False)
    op.create_index(op.f('ix_scholarships_department_id'), 'scholarships', ['department_id'], unique=False)
    op.create_index(op.f('ix_scholarships_state_id'), 'scholarships', ['state_id'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("connector_type IN ('html', 'dynamic', 'pdf', 'tabular', 'json')", name=op.f('ck_sources_connector_type')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_sources_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('source_url', name=op.f('uq_sources_source_url'))
    )
    op.create_index(op.f('ix_sources_department_id'), 'sources', ['department_id'], unique=False)
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    op.create_table('action_dossiers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('scheme_name', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'ready', 'failed')", name=op.f('ck_action_dossiers_status')),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_action_dossiers_scheme_id_schemes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_dossiers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_dossiers'))
    )
    op.create_index(op.f('ix_action_dossiers_scheme_id'), 'action_dossiers', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_action_dossiers_user_id'), 'action_dossiers', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_type IN ('NEW_SCHEME_MATCH', 'DEADLINE_APPROACHING', 'RULE_MODIFIED')", name=op.f('ck_alerts_alert_type')),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_alerts_scheme_id_schemes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('user_id', 'scheme_id', 'alert_type', name=op.f('uq_alerts_user_id'))
    )
    op.create_index(op.f('ix_alerts_scheme_id'), 'alerts', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('ingestion_logs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('rows_upserted', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'ok', 'failed')", name=op.f('ck_ingestion_logs_status')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_logs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_logs'))
    )
    op.create_index(op.f('ix_ingestion_logs_content_hash'), 'ingestion_logs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ingestion_logs_source_id'), 'ingestion_logs', ['source_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('uri', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_documents_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('source_id', 'content_hash', name=op.f('uq_source_documents_source_id'))
    )
    op.create_index(op.f('ix_source_documents_content_hash'), 'source_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_documents_source_id'), 'source_documents', ['source_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('land_hectares', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=8), nullable=True),
    sa.Column('occupation', sa.String(length=32), nullable=True),
    sa.Column('state_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('consent_retention', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IS NULL OR category IN ('GEN', 'OBC', 'SC', 'ST', 'EWS')", name=op.f('ck_user_profiles_category')),
    sa.CheckConstraint("gender IS NULL OR gender IN ('any', 'female', 'male')", name=op.f('ck_user_profiles_gender')),
    sa.CheckConstraint("occupation IS NULL OR occupation IN ('farmer', 'student', 'artisan', 'shg', 'other')", name=op.f('ck_user_profiles_occupation')),
    sa.CheckConstraint('age IS NULL OR (age >= 0 AND age <= 120)', name=op.f('ck_user_profiles_age_bounds')),
    sa.CheckConstraint('income IS NULL OR income >= 0', name=op.f('ck_user_profiles_income_non_negative')),
    sa.CheckConstraint('land_hectares IS NULL OR land_hectares >= 0', name=op.f('ck_user_profiles_land_non_negative')),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_user_profiles_district_id_districts')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_user_profiles_state_id_states')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_index(op.f('ix_user_profiles_district_id'), 'user_profiles', ['district_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_state_id'), 'user_profiles', ['state_id'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('dims', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_document_embeddings_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_embeddings')),
    sa.UniqueConstraint('source_document_id', 'chunk_index', 'model_name', name=op.f('uq_document_embeddings_source_document_id'))
    )
    op.create_index(op.f('ix_document_embeddings_source_document_id'), 'document_embeddings', ['source_document_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('gazette_ref', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name=op.f('ck_policy_versions_effective_window')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_versions_policy_id_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_policy_versions_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('policy_id', 'version_number', name=op.f('uq_policy_versions_policy_id'))
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_source_document_id'), 'policy_versions', ['source_document_id'], unique=False)
    op.create_table('scheme_versions',
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_hi', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_hi', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name=op.f('ck_scheme_versions_effective_window')),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_scheme_versions_scheme_id_schemes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_scheme_versions_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_versions')),
    sa.UniqueConstraint('scheme_id', 'version_number', name=op.f('uq_scheme_versions_scheme_id'))
    )
    op.create_index(op.f('ix_scheme_versions_scheme_id'), 'scheme_versions', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_versions_source_document_id'), 'scheme_versions', ['source_document_id'], unique=False)
    op.create_table('benefits',
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('label_hi', sa.String(length=300), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('amount_text', sa.String(length=300), nullable=False),
    sa.Column('periodicity', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_versions.id'], name=op.f('fk_benefits_scheme_version_id_scheme_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benefits'))
    )
    op.create_index(op.f('ix_benefits_scheme_version_id'), 'benefits', ['scheme_version_id'], unique=False)
    op.create_table('eligibility_rules',
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ast_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('income_limit', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('age', 'income', 'land', 'gender', 'category', 'occupation', 'always')", name=op.f('ck_eligibility_rules_kind')),
    sa.CheckConstraint('age_min IS NULL OR age_max IS NULL OR age_min <= age_max', name=op.f('ck_eligibility_rules_age_range')),
    sa.CheckConstraint('income_limit IS NULL OR income_limit >= 0', name=op.f('ck_eligibility_rules_income_non_negative')),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_versions.id'], name=op.f('fk_eligibility_rules_scheme_version_id_scheme_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_rules'))
    )
    op.create_index(op.f('ix_eligibility_rules_scheme_version_id'), 'eligibility_rules', ['scheme_version_id'], unique=False)
    op.create_table('policy_changes',
    sa.Column('from_version_id', sa.Uuid(), nullable=False),
    sa.Column('to_version_id', sa.Uuid(), nullable=False),
    sa.Column('change_kind', sa.String(length=16), nullable=False),
    sa.Column('clause_ref', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('numeric_old', sa.Float(), nullable=True),
    sa.Column('numeric_new', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("change_kind IN ('added', 'removed', 'amended', 'numeric')", name=op.f('ck_policy_changes_change_kind')),
    sa.ForeignKeyConstraint(['from_version_id'], ['policy_versions.id'], name=op.f('fk_policy_changes_from_version_id_policy_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_version_id'], ['policy_versions.id'], name=op.f('fk_policy_changes_to_version_id_policy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_changes'))
    )
    op.create_index(op.f('ix_policy_changes_from_version_id'), 'policy_changes', ['from_version_id'], unique=False)
    op.create_index(op.f('ix_policy_changes_to_version_id'), 'policy_changes', ['to_version_id'], unique=False)
    op.create_table('policy_clauses',
    sa.Column('policy_version_id', sa.Uuid(), nullable=False),
    sa.Column('clause_ref', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_policy_clauses_policy_version_id_policy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_clauses'))
    )
    op.create_index(op.f('ix_policy_clauses_policy_version_id'), 'policy_clauses', ['policy_version_id'], unique=False)
    op.create_table('required_documents',
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_versions.id'], name=op.f('fk_required_documents_scheme_version_id_scheme_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_required_documents'))
    )
    op.create_index(op.f('ix_required_documents_scheme_version_id'), 'required_documents', ['scheme_version_id'], unique=False)
    op.create_foreign_key(
        'fk_schemes_current_version',
        'schemes',
        'scheme_versions',
        ['current_version_id'],
        ['id'],
    )
    op.create_foreign_key(
        'fk_policies_current_version',
        'policies',
        'policy_versions',
        ['current_version_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_schemes_current_version', 'schemes', type_='foreignkey')
    op.drop_constraint('fk_policies_current_version', 'policies', type_='foreignkey')
    op.drop_index(op.f('ix_required_documents_scheme_version_id'), table_name='required_documents')
    op.drop_table('required_documents')
    op.drop_index(op.f('ix_policy_clauses_policy_version_id'), table_name='policy_clauses')
    op.drop_table('policy_clauses')
    op.drop_index(op.f('ix_policy_changes_to_version_id'), table_name='policy_changes')
    op.drop_index(op.f('ix_policy_changes_from_version_id'), table_name='policy_changes')
    op.drop_table('policy_changes')
    op.drop_index(op.f('ix_eligibility_rules_scheme_version_id'), table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    op.drop_index(op.f('ix_benefits_scheme_version_id'), table_name='benefits')
    op.drop_table('benefits')
    op.drop_index(op.f('ix_scheme_versions_source_document_id'), table_name='scheme_versions')
    op.drop_index(op.f('ix_scheme_versions_scheme_id'), table_name='scheme_versions')
    op.drop_table('scheme_versions')
    op.drop_index(op.f('ix_policy_versions_source_document_id'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_document_embeddings_source_document_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_user_profiles_state_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_district_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_source_documents_source_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_content_hash'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_ingestion_logs_source_id'), table_name='ingestion_logs')
    op.drop_index(op.f('ix_ingestion_logs_content_hash'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_scheme_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_action_dossiers_user_id'), table_name='action_dossiers')
    op.drop_index(op.f('ix_action_dossiers_scheme_id'), table_name='action_dossiers')
    op.drop_table('action_dossiers')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_index(op.f('ix_sources_department_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_scholarships_state_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_department_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_deadline'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_content_hash'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_schemes_status'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_state_id'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_department_id'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_jobs_state_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_department_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_deadline'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_internships_state_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_department_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_deadline'), table_name='internships')
    op.drop_index(op.f('ix_internships_content_hash'), table_name='internships')
    op.drop_table('internships')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_table('roles')
    op.drop_table('policies')
    op.drop_table('departments')
    # ### end Alembic commands ###
