import type { SchemeRecord } from '@/types';

/** Public, official-scheme facts used until the Phase 7 ingestion tables are live. */
export const OFFICIAL_SCHEME_CATALOG: SchemeRecord[] = [
  {
    id: 'pm-kisan',
    code: 'PM-KISAN',
    name: 'PM-Kisan Samman Nidhi',
    nameHi: 'प्रधानमंत्री किसान सम्मान निधि',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    ministryHi: 'कृषि एवं किसान कल्याण मंत्रालय',
    category: 'agriculture',
    badge: 'Direct Benefit Transfer · Central',
    badgeHi: 'प्रत्यक्ष लाभ अंतरण · केंद्रीय',
    summary: 'Income support for landholding farmer families through three instalments each year.',
    summaryHi: 'भूमिधारक किसान परिवारों को वर्ष में तीन किस्तों में आय सहायता।',
    benefit: '₹6,000 / year',
    benefitHi: '₹6,000 / वर्ष',
    documents: [
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
      { id: 'land', label: 'Land registry' },
      { id: 'bank', label: 'Bank account proof' },
    ],
    rules: [
      { id: 'land', label: 'Landholding farmer family', detail: 'Requires recorded agricultural land', kind: 'land', min: 0.01 },
      { id: 'income-not-excluded', label: 'Not in excluded high-income posts', detail: 'Constitutional / professional exclusions apply at source', kind: 'always' },
    ],
    sourceUrl: 'https://pmkisan.gov.in',
  },
  {
    id: 'pmfby',
    code: 'PMFBY',
    name: 'Pradhan Mantri Fasal Bima Yojana',
    nameHi: 'प्रधानमंत्री फसल बीमा योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    ministryHi: 'कृषि एवं किसान कल्याण मंत्रालय',
    category: 'agriculture',
    badge: 'Insurance · Central',
    badgeHi: 'बीमा · केंद्रीय',
    summary: 'Crop insurance against natural calamities, pests and diseases for notified crops.',
    summaryHi: 'अधिसूचित फसलों पर प्राकृतिक आपदा, कीट और रोग के विरुद्ध फसल बीमा।',
    benefit: 'Sum insured per hectare',
    benefitHi: 'प्रति हेक्टेयर बीमित राशि',
    documents: [
      { id: 'land', label: 'Land registry' },
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
    ],
    rules: [
      { id: 'land', label: 'Cultivator of notified crop', detail: 'Land or tenant cultivator record', kind: 'land', min: 0.01 },
    ],
    sourceUrl: 'https://pmfby.gov.in',
  },
  {
    id: 'pmmvy',
    code: 'PMMVY',
    name: 'Pradhan Mantri Matru Vandana Yojana',
    nameHi: 'प्रधानमंत्री मातृ वंदना योजना',
    ministry: 'Ministry of Women & Child Development',
    ministryHi: 'महिला एवं बाल विकास मंत्रालय',
    category: 'women',
    badge: 'DBT · Maternity',
    badgeHi: 'डीबीटी · मातृत्व',
    summary: 'Cash incentive for pregnant and lactating mothers for the first living child.',
    summaryHi: 'प्रथम जीवित बच्चे के लिए गर्भवती और स्तनपान कराने वाली माताओं को नकद प्रोत्साहन।',
    benefit: '₹5,000',
    benefitHi: '₹5,000',
    documents: [
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
      { id: 'mcp', label: 'MCP / pregnancy card' },
    ],
    rules: [
      { id: 'gender', label: 'Woman beneficiary', detail: 'Registered pregnant / lactating mother', kind: 'gender', equals: 'female' },
      { id: 'age', label: 'Age 18+', detail: 'Adult mother at registration', kind: 'age', min: 18 },
    ],
    sourceUrl: 'https://wcd.nic.in',
  },
  {
    id: 'nrlm',
    code: 'DAY-NRLM',
    name: 'Deendayal Antyodaya Yojana — NRLM',
    nameHi: 'दीनदयाल अंत्योदय योजना — एनआरएलएम',
    ministry: 'Ministry of Rural Development',
    ministryHi: 'ग्रामीण विकास मंत्रालय',
    category: 'women',
    badge: 'Livelihood · SHG',
    badgeHi: 'आजीविका · स्वयं सहायता समूह',
    summary: 'Self-help group formation, credit linkage and livelihood support for rural women.',
    summaryHi: 'ग्रामीण महिलाओं के लिए स्वयं सहायता समूह, ऋण लिंकेज और आजीविका सहयोग।',
    benefit: 'SHG credit linkage',
    benefitHi: 'एसएचजी ऋण लिंकेज',
    documents: [
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
      { id: 'shg', label: 'SHG membership' },
    ],
    rules: [
      { id: 'gender', label: 'Rural woman / SHG member', detail: 'Designed around women’s collectives', kind: 'gender', equals: 'female' },
    ],
    sourceUrl: 'https://aajeevika.gov.in',
  },
  {
    id: 'nsp-pms',
    code: 'NSP-PMS',
    name: 'Post Matric Scholarship (SC)',
    nameHi: 'पोस्ट मैट्रिक छात्रवृत्ति (अनुसूचित जाति)',
    ministry: 'Department of Social Justice & Empowerment',
    ministryHi: 'सामाजिक न्याय एवं अधिकारिता विभाग',
    category: 'education',
    badge: 'Scholarship · Central',
    badgeHi: 'छात्रवृत्ति · केंद्रीय',
    summary: 'Tuition and maintenance support for SC students studying after class 10.',
    summaryHi: 'कक्षा 10 के बाद पढ़ने वाले अनुसूचित जाति के विद्यार्थियों को शुल्क और भरण-पोषण सहायता।',
    benefit: 'Tuition + maintenance',
    benefitHi: 'शुल्क + भरण-पोषण',
    documents: [
      { id: 'caste', label: 'Caste certificate' },
      { id: 'income', label: 'Income certificate' },
      { id: 'enrolment', label: 'Institute enrolment' },
    ],
    rules: [
      { id: 'cat', label: 'SC category', detail: 'Valid caste certificate', kind: 'category', includes: ['SC'] },
      { id: 'income', label: 'Parental income ceiling', detail: 'Typically ≤ ₹2.5 lakh (verify current gazette)', kind: 'income', max: 250000 },
      { id: 'age', label: 'Student age band', detail: 'Post-matric learner', kind: 'age', min: 16, max: 35 },
    ],
    sourceUrl: 'https://scholarships.gov.in',
  },
  {
    id: 'nsp-obc',
    code: 'NSP-OBC',
    name: 'Post Matric Scholarship (OBC)',
    nameHi: 'पोस्ट मैट्रिक छात्रवृत्ति (ओबीसी)',
    ministry: 'Ministry of Social Justice & Empowerment',
    ministryHi: 'सामाजिक न्याय एवं अधिकारिता मंत्रालय',
    category: 'education',
    badge: 'Scholarship · Central',
    badgeHi: 'छात्रवृत्ति · केंद्रीय',
    summary: 'Post-matric support for OBC students within the notified income ceiling.',
    summaryHi: 'अधिसूचित आय सीमा के भीतर ओबीसी विद्यार्थियों के लिए पोस्ट-मैट्रिक सहायता।',
    benefit: 'Tuition support',
    benefitHi: 'शुल्क सहायता',
    documents: [
      { id: 'caste', label: 'OBC certificate' },
      { id: 'income', label: 'Income certificate' },
    ],
    rules: [
      { id: 'cat', label: 'OBC category', detail: 'Valid OBC certificate', kind: 'category', includes: ['OBC'] },
      { id: 'income', label: 'Income ≤ ₹2.5 lakh', detail: 'Confirm latest ceiling in the gazette', kind: 'income', max: 250000 },
    ],
    sourceUrl: 'https://scholarships.gov.in',
  },
  {
    id: 'pm-scholarship',
    code: 'PMSS',
    name: 'Prime Minister’s Scholarship Scheme',
    nameHi: 'प्रधानमंत्री छात्रवृत्ति योजना',
    ministry: 'Ministry of Defence / Home Affairs (Wards)',
    ministryHi: 'रक्षा / गृह मंत्रालय (आश्रित)',
    category: 'education',
    badge: 'Scholarship · Professional',
    badgeHi: 'छात्रवृत्ति · व्यावसायिक',
    summary: 'Scholarship for professional degree courses for eligible wards of service personnel.',
    summaryHi: 'सेवा कर्मियों के पात्र आश्रितों के लिए व्यावसायिक डिग्री पाठ्यक्रमों पर छात्रवृत्ति।',
    benefit: '₹2,500–3,000 / month',
    benefitHi: '₹2,500–3,000 / माह',
    documents: [
      { id: 'enrolment', label: 'Institute enrolment' },
      { id: 'service', label: 'Service dependency proof' },
    ],
    rules: [
      { id: 'age', label: 'Higher-education age', detail: 'Typically 17–25 at entry', kind: 'age', min: 17, max: 30 },
      { id: 'occ', label: 'Student track', detail: 'Enrolled in notified professional course', kind: 'occupation', includes: ['student'] },
    ],
    sourceUrl: 'https://scholarships.gov.in',
  },
  {
    id: 'ayushman',
    code: 'PM-JAY',
    name: 'Ayushman Bharat — PM-JAY',
    nameHi: 'आयुष्मान भारत — पीएम-जेएवाई',
    ministry: 'Ministry of Health & Family Welfare',
    ministryHi: 'स्वास्थ्य एवं परिवार कल्याण मंत्रालय',
    category: 'health',
    badge: 'Health cover · Central',
    badgeHi: 'स्वास्थ्य कवर · केंद्रीय',
    summary: 'Hospitalisation cover for eligible poor and vulnerable families in empaneled hospitals.',
    summaryHi: 'सूचीबद्ध अस्पतालों में पात्र गरीब और संवेदनशील परिवारों के लिए अस्पताल भर्ती कवर।',
    benefit: '₹5 lakh / family / year',
    benefitHi: '₹5 लाख / परिवार / वर्ष',
    documents: [
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
      { id: 'ration', label: 'Ration / SECC eligibility' },
    ],
    rules: [
      { id: 'income', label: 'SECC / NFSA-linked eligibility', detail: 'Not a simple income cut-off — deprivation criteria apply', kind: 'income', max: 300000 },
    ],
    sourceUrl: 'https://nha.gov.in',
  },
  {
    id: 'ig-oldage',
    code: 'NSAP-IGNOAPS',
    name: 'Indira Gandhi National Old Age Pension',
    nameHi: 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन',
    ministry: 'Ministry of Rural Development',
    ministryHi: 'ग्रामीण विकास मंत्रालय',
    category: 'health',
    badge: 'Pension · NSAP',
    badgeHi: 'पेंशन · एनएसएपी',
    summary: 'Monthly pension for below-poverty-line senior citizens.',
    summaryHi: 'गरीबी रेखा से नीचे के वरिष्ठ नागरिकों के लिए मासिक पेंशन।',
    benefit: '₹200–500 / month (central share)',
    benefitHi: '₹200–500 / माह (केंद्र हिस्सा)',
    documents: [
      { id: 'age-proof', label: 'Age proof' },
      { id: 'bpl', label: 'BPL / NSAP list' },
    ],
    rules: [
      { id: 'age', label: 'Age 60+', detail: 'Lower rate 60–79, higher 80+', kind: 'age', min: 60 },
      { id: 'income', label: 'BPL household', detail: 'State BPL / NSAP identification', kind: 'income', max: 120000 },
    ],
    sourceUrl: 'https://nsap.nic.in',
  },
  {
    id: 'pm-vishwakarma',
    code: 'PM-VISHWAKARMA',
    name: 'PM Vishwakarma',
    nameHi: 'पीएम विश्वकर्मा',
    ministry: 'Ministry of Micro, Small & Medium Enterprises',
    ministryHi: 'सूक्ष्म, लघु एवं मध्यम उद्यम मंत्रालय',
    category: 'msme',
    badge: 'Artisan credit · Central',
    badgeHi: 'कारीगर ऋण · केंद्रीय',
    summary: 'Toolkit, skilling and collateral-free credit for traditional artisans and craftspeople.',
    summaryHi: 'पारंपरिक कारीगरों के लिए टूलकिट, कौशल और बिना गारंटी का ऋण।',
    benefit: '₹1–2 lakh credit slabs',
    benefitHi: '₹1–2 लाख ऋण स्लैब',
    documents: [
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
      { id: 'artisan', label: 'Trade / artisan proof' },
    ],
    rules: [
      { id: 'occ', label: 'Traditional artisan trade', detail: 'Notified Vishwakarma trades', kind: 'occupation', includes: ['artisan'] },
    ],
    sourceUrl: 'https://pmvishwakarma.gov.in',
  },
  {
    id: 'pmegp',
    code: 'PMEGP',
    name: 'Prime Minister’s Employment Generation Programme',
    nameHi: 'प्रधानमंत्री रोजगार सृजन कार्यक्रम',
    ministry: 'Ministry of MSME',
    ministryHi: 'एमएसएमई मंत्रालय',
    category: 'msme',
    badge: 'Enterprise credit · KVIC',
    badgeHi: 'उद्यम ऋण · केवीआईसी',
    summary: 'Margin-money subsidy for new micro-enterprises in manufacturing and services.',
    summaryHi: 'विनिर्माण और सेवाओं में नए सूक्ष्म उद्यमों के लिए मार्जिन-मनी सब्सिडी।',
    benefit: '15–35% margin subsidy',
    benefitHi: '15–35% मार्जिन सब्सिडी',
    documents: [
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
      { id: 'project', label: 'Project report' },
      { id: 'caste', label: 'Category certificate if claimed' },
    ],
    rules: [
      { id: 'age', label: 'Age 18+', detail: 'Adult first-generation entrepreneur', kind: 'age', min: 18 },
      { id: 'occ', label: 'Enterprise / artisan / SHG track', detail: 'New unit, not an existing large enterprise', kind: 'occupation', includes: ['artisan', 'shg', 'other', 'farmer'] },
    ],
    sourceUrl: 'https://www.kviconline.gov.in',
  },
  {
    id: 'mudra',
    code: 'PMMY',
    name: 'Pradhan Mantri MUDRA Yojana',
    nameHi: 'प्रधानमंत्री मुद्रा योजना',
    ministry: 'Department of Financial Services',
    ministryHi: 'वित्तीय सेवाएँ विभाग',
    category: 'msme',
    badge: 'Collateral-free credit',
    badgeHi: 'बिना गारंटी ऋण',
    summary: 'Shishu, Kishore and Tarun loans for non-farm income-generating micro units.',
    summaryHi: 'गैर-कृषि आय इकाइयों के लिए शिशु, किशोर और तरुण ऋण।',
    benefit: 'Up to ₹20 lakh (Tarun Plus)',
    benefitHi: '₹20 लाख तक (तरुण प्लस)',
    documents: [
      { id: 'aadhaar', label: 'Aadhaar (masked locally)' },
      { id: 'bank', label: 'Bank KYC (not stored as digits)' },
    ],
    rules: [
      { id: 'age', label: 'Age 18+', detail: 'Bankable adult applicant', kind: 'age', min: 18 },
    ],
    sourceUrl: 'https://www.mudra.org.in',
  },
];
